### ISSUE TITLE
missing link or photo in README.md

### ISSUE THREAD

**Issue by phwelo** [boredland/manjaro-sway#15]
> enable this flag to allow screensharing in chromium

which flag?

is it still `--enable-features=UseOzonePlatform --ozone-platform=wayland`?

**Comment by boredland** [comment]
apparently chrome or github are filtering the link, it is there :D - will add it as text too.
https://github.com/boredland/manjaro-sway/commit/992a9ec7f2e78c4aff91377b1ca902fef728bcaf
