### ISSUE TITLE
Wrong credentials in last iso

### ISSUE THREAD

**Issue by Andrea485** [boredland/manjaro-sway#17]

**Comment by lluisYasT** [comment]
Yes, 
user: manjaro
password: manjaro
These credentials don't work.

**Comment by Aabayoumy** [comment]
root
manjaro

working for me :)

**Comment by 1337omega** [comment]
> root
> manjaro
> 
> working for me :)

Didnt work for me neither

**Comment by jnslmk** [comment]
> root
> manjaro
> 
> working for me :)

For me neither

**Comment by lluisYasT** [comment]
> root
> manjaro
> 
> working for me :)

They don't work for me either on the release 202101012325

**Comment by Aabayoumy** [comment]
root not work in GUI
CTL+Alt +F3 
Login with root and create your user and copy the .config 
files

**Comment by boredland** [comment]
hi there! seems I broke sth. in the iso overlay. the more recent images should have working credentials again.
