### ISSUE TITLE
ISO needs a more recent kernel to support Ryzen 5

### ISSUE THREAD

**Issue by angelus2014** [boredland/manjaro-sway#25]
Hello,

The current ISO can't boot properly on a Ryzen 5 (4500U in my case) as the 5.4 kernel doesn't support the GPU inside the Ryzen CPU.

Regards,

Angelo

**Comment by boredland** [comment]
which kernel do we need?

**Comment by boredland** [comment]
ok, will go with kernel59 as the official xfce iso does.

**Comment by angelus2014** [comment]
> which kernel do we need?

Anything from 5.8 and higher will work. Perhaps lower as well, but I've never tested those. Usually I stay with LTS kernels, but for some reason Manjaro hasn't marked the 5.10 as being LTS.

Regards,

Angelo

**Comment by boredland** [comment]
its on kernel 59 now
