### ISSUE TITLE
User lacks permissions to adjust brightness or toggle bluetooth

### ISSUE THREAD

**Issue by kblcuk** [boredland/manjaro-sway#28]
First of thanks for the amazing work you've done so far :tada: I've spent ridiculous amount of hours battling hidpi issues with X11-based Manjaro i3 version (it _almost_ works, except every app decided that it needs a slightly different mouse cursor size, which drives my OCD nuts), and this Sway-based config just magically works on my Lenovo X1e.

I had to add my user to `video` and `rfkill` groups so that media buttons to adjust brightness and bluetooth work. Without those
- `light -v 3 -S 50` would complain that it can't modify `/sys/class/backlight/intel_backlight/brightness` (and checking permissions for it shows that it's owned by root and in `video` group)
- turning bluetooth off via blueberry fails, and error message mentions that user is not in `rfkill` group.

I tried finding out where would newly created user's permissions be set, but didn't really find anything (although I didn't look further than your own https://github.com/boredland/iso-profiles and https://github.com/boredland/manjaro-sway-settings repositories, so it might as well be somewhere further up the chain). If you have any idea where those are set, feel free to point me to that place, and I'll make a PR.

So far I just did 
```
usermod -a -G video $USER
usermod -a -G rfkill $USER
```
locally to get media buttons working.

Thanks again!

**Comment by boredland** [comment]
yeah. I don't know when and why I removed that as additional groups. is fixed in the profile and will land soon.
